# Generated by Django 6.0.6 on 2026-06-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('precision_macro', models.FloatField()),
                ('recall_macro', models.FloatField()),
                ('f1_macro', models.FloatField()),
                ('test_samples', models.IntegerField()),
                ('label_classes', models.JSONField(default=list)),
                ('full_report', models.JSONField(default=dict, help_text='Full classification_report dict')),
            ],
            options={
                'verbose_name': 'Training Run',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PhD', 'PhD')], default='Bachelor', max_length=20)),
                ('skills', models.TextField(default='None', help_text='Comma-separated list of skills')),
                ('certifications', models.TextField(default='None', help_text='Comma-separated certifications')),
                ('experience_score', models.FloatField(default=5.0, help_text='Averaged years + projects (0-10)')),
                ('cgpa', models.FloatField(default=70.0, help_text='Academic score or AI compatibility (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_career', models.CharField(max_length=100)),
                ('confidence', models.FloatField(help_text='Probability of the top predicted class')),
                ('probabilities', models.JSONField(default=dict, help_text='Full {career: probability} mapping from predict_proba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.userprofile')),
            ],
            options={
                'verbose_name': 'Recommendation Log',
                'ordering': ['-created_at'],
            },
        ),
    ]
